### ISSUE TITLE
Investigate combining fastapi and python project templates

### ISSUE THREAD

**Issue by lucasmelin** [bocdaz/template-python-project#6]
<p>As a developer productivity team member, I want to be able to apply changes to all the template projects at the same time, so that it's easy to keep the templates in sync.</p>

<p><a href="https://github.com/cookiecutter/cookiecutter" class="external-link" target="_blank" rel="nofollow noopener">cookiecutter</a> is being used for template-python-fastapi, could use it to combine our two template repos into one and use conditional logic at runtime to include/remove pieces.</p>

- [x] bocdaz/bocdaz-config#24
- [x] bocdaz/python-project-template-repository#1
- [x] bocdaz/fastapi-app-template-repository#1
- [x] #11
<i>[DEV-208] created by mell</i>

**Comment by slougheed** [comment]
All tasks completed
